name: Build React App

on:
  push:
    branches: [ main ]
    paths:
      - 'mw-tools/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Dependencies
      working-directory: ./mw-tools
      run: npm install
      
    - name: Build Project
      working-directory: ./mw-tools
      run: npm run build
      
    - name: Upload Build Files
      uses: actions/upload-artifact@v4
      with:
        name: mw-tools-build
        path: ./mw-tools/dist
